"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['mqtt_gui.py']
DATA_FILES = [
    'mqtt_client.py',
    'item_callbacks.py',
    'init_values.py',
    'init_funcs.py',
    'utils.py',
    # 'img/logo_bm_new.png',
    # 'fonts/SFMono-Regular.otf',
    # 'fonts/SourceCodePro-Bold.otf',
    # 'fonts/SourceCodePro-Regular.otf',
    # 'fonts/SourceHanSansSC-Normal.otf',
    # 'fonts/SourceSerif4-Regular.otf',
    ]
OPTIONS = {
    'includes':[
        'dearpygui',
        'paho-mqtt',
        'pyperclip',
    ]
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
